name: PR Verification
on:
  workflow_dispatch:
  push:
    branches:
      - main

# concurrency:
#   group: ${{ github.head_ref == '' && github.ref || github.head_ref }}
#   cancel-in-progress: true

jobs:
  wf1:
    name: WF1
    uses: ./.github/workflows/wf1.yml
    secrets: inherit

  wf2:
    name: WF2
    uses: ./.github/workflows/wf2.yml
    secrets: inherit

  check-failed-jobs:
    name: Check and Notify Failed Jobs
    needs: [wf1, wf2]
    if: always()
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Check Failed Jobs
        id: check-failed-jobs
        run: |
          FAILED_JOBS=$(gh run view ${{ github.run_id }} --json jobs --jq '[.jobs[] | select(.conclusion=="failure") | {name: .name, conclusion: .conclusion}]')
          ESCAPED_FAILED_JOBS=$(echo "$FAILED_JOBS" | tr -d '\n' | jq -aRs .)
          if [[ "$ESCAPED_FAILED_JOBS" != "\"[]\"" ]]; then
            MESSAGE=$(echo "$FAILED_JOBS" | jq -r '.[] | "\(.name): \(.conclusion)"' | tr '\n' ' ')
            echo "There are failed jobs: $MESSAGE"
            echo "::set-output name=failed_jobs::$MESSAGE"
            exit 1
          else
            echo "No failed jobs!"
            echo "::set-output name=failed_jobs::No failed jobs!"
          fi

      - name: Print output
        run: |
          echo ${{ steps.check-failed-jobs.outputs.failed_jobs }}

