name: PR Verification
on:
  workflow_dispatch:
  push:
    branches:
      - main

# concurrency:
#   group: ${{ github.head_ref == '' && github.ref || github.head_ref }}
#   cancel-in-progress: true

jobs:
  wf1:
    name: WF1
    uses: ./.github/workflows/wf1.yml
    secrets: inherit

  wf2:
    name: WF2
    uses: ./.github/workflows/wf2.yml
    secrets: inherit

  check-failed-jobs:
    name: Check and Notify Failed Jobs
    needs: [wf1, wf2]
    if: always()
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Check Failed Jobs
        id: check-failed-jobs
        run: |
          # Fetch failed jobs
          FAILED_JOBS=$(gh run view ${{ github.run_id }} --json jobs --jq '[.jobs[] | select(.conclusion=="failure") | {name: .name, conclusion: .conclusion}]')
          
          # Check if there are any failed jobs
          ESCAPED_FAILED_JOBS=$(echo "$FAILED_JOBS" | tr -d '\n' | jq -aRs .)
          if [[ "$ESCAPED_FAILED_JOBS" != "\"[]\"" ]]; then
            echo "There are failed jobs:"
            
            # Parse and print each failed job
            MESSAGE=$(echo "$FAILED_JOBS" | jq -r '.[] | "\(.name): \(.conclusion)"' | tr '\n' ' ')
            echo "failed_jobs=$MESSAGE" >> $GITHUB_OUTPUT
            
            exit 1
          else
            echo "failed_jobs=No failed jobs!" >> $GITHUB_OUTPUT
          fi

      - name: Print output
        run: |
          echo ${{ steps.check-failed-jobs.outputs.failed_jobs }}

