name: First Workflow
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["First Cron Job"]
    types:
      - completed

env:
  mobile_default_version: 130000

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: git
        id: artifact-version
        run: echo "mobversion=$(git log develop --oneline | wc -l)" >> $GITHUB_OUTPUT

      - name: Count Commits
        run: |
          commit_count=$(git log --oneline --branches="main" | wc -l)
          echo "Number of commits: $commit_count"
          echo "New version ${{ mobile_default_version }} + ${{ steps.artifact-version.outputs.mobversion }}"

      - name: Print Goodbye
        run: echo "Done- Bye!!"
