name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      timeoutValue:
        description: 'Provide timeout minutes to cancel job'
        required: false
        type: string
  workflow_run:
    workflows: ["First Cron Job"]
    types:
      - completed
  # schedule:
  #   - cron: '*/10 * * * *'

env:
  MOBILE_DEFAULT_VERSION: 130000
  timeoutValue: '${{ inputs.timeoutValue || vars.TIMEOUT_VALUE }}'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: git
        id: artifact-version
        run: |
          echo "mobversion=$(git log develop --oneline | wc -l)" >> $GITHUB_OUTPUT
          echo ${{ vars.TIMEOUT_VALUE }}
          echo ${{ env.timeoutValue }}
          echo "The above is timeout Value from GH vars"
          echo ${{ github.repository_owner }} (repo organization)
          ${{ github.repository }} (repo name)

      - name: Count Commits
        run: |
          result_add=$(($MOBILE_DEFAULT_VERSION + $(git log develop --oneline | wc -l)))
          echo "Addition: $result_add"

      - name: Print Goodbye
        run: echo "Done- Bye!!"
