name: First Workflow
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["First Cron Job"]
    types:
      - completed
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: git
        run: |
          git rev-list --count --all

      - name: Count Commits
        run: |
          commit_count=$(git log --oneline --branches="main" | wc -l)
          echo "Number of commits: $commit_count"

      - name: Print Goodbye
        run: echo "Done- Bye!!"
