name: First Workflow
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["First Cron Job"]
    types:
      - completed

env:
  MOBILE_DEFAULT_VERSION: 130000

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: git
        id: artifact-version
        run: echo "mobversion=$(git log develop --oneline | wc -l)" >> $GITHUB_OUTPUT

      - name: Count Commits
        run: |
          result_add=$(($MOBILE_DEFAULT_VERSION + $(git log develop --oneline | wc -l)))
          echo "Addition: $result_add"

      - name: Print Goodbye
        run: echo "Done- Bye!!"
