name: First Workflow
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["First Cron Job"]
    types:
      - completed
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: git
        run: |
          git rev-list --count --all

      - name: Count Commits
        run: |
          branch=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.before != '0000000000000000000000000000000000000000' && github.event.after != '0000000000000000000000000000000000000000' && echo "main" || echo "other" }}
          if [[ $branch == "other" ]]; then
            branch=null
          fi
          commit_count=$(git log --oneline --branches="$branch" | wc -l)
          echo "Number of commits: $commit_count"

      - name: Print Goodbye
        run: echo "Done- Bye!!"
