name: First Workflow
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["First Cron Job"]
    types:
      - completed
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World this ran from first CRON GHA"

      - name: Print Goodbye
        run: echo "Done- Bye!!"
