name: PR-non-emulator-verification
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'The tag of the image to use for the container'
        required: true
        type: string
        default: latest

  workflow_call:
    inputs:
      image-tag:
        description: 'The tag of the image to use for the container'
        required: false
        type: string
        default: latest

jobs:
  debug:
      name: Debug
      runs-on: ubuntu-latest
      steps:
        - name: Debug echo
          run: |
            echo "Hello from No Emu"
            exit 1
        - name: Debug 2
          run: |
            echo "Hello from the 2nd step"
            
        - name: Debug 3
          run: |
            echo "Hello from the 3rd step"

        - name: Debug 4
          run: |
            echo "Hello from the 4th step"
