name: PR Verification

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'Dockerfile'

  schedule:
    - cron: '30 2,20 * * *'

jobs:
  non-emulator-verification:
    name: Non Emulator Verification
    uses: ./.github/workflows/pr-non-emulator-verification.yml
    secrets: inherit
    concurrency: pr-verification

  emulator-verification:
    name: Emulator Verification
    uses: ./.github/workflows/pr-emulator-verification.yml
    secrets: inherit
    concurrency: pr-verification

  cancel-other-job:
    name: Cancel Other Job
    runs-on: ubuntu-latest
    needs: 
      - non-emulator-verification
      - emulator-verification
    if: failure()
    steps:
      - name: Cancel Non Emulator Verification if Emulator Verification fails
        if: failure() && needs.emulator-verification.result == 'failure'
        run: |
          gh run cancel --job-name non-emulator-verification --repo ${{ github.repository }}

      - name: Cancel Emulator Verification if Non Emulator Verification fails
        if: failure() && needs.non-emulator-verification.result == 'failure'
        run: |
          gh run cancel --job-name emulator-verification --repo ${{ github.repository }}
