name: PR Verification

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'Dockerfile'

  schedule:
    - cron: '30 2,20 * * *'

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [non-emulator, emulator]
    steps:
      - name: Run Verification Job
        uses: ./.github/workflows/pr-${{ matrix.job }}-verification.yml
        secrets: inherit

  monitor:
    name: Monitor Jobs
    runs-on: ubuntu-latest
    needs: [verification]
    steps:
      - name: Check Results
        run: |
          if [ "${{ needs.verification.outputs['non-emulator'] }}" == "failure" ]; then
            echo "Non Emulator Verification failed. Canceling Emulator Verification..."
            gh run cancel --job-name emulator --repo ${{ github.repository }}
          elif [ "${{ needs.verification.outputs['emulator'] }}" == "failure" ]; then
            echo "Emulator Verification failed. Canceling Non Emulator Verification..."
            gh run cancel --job-name non-emulator --repo ${{ github.repository }}
          fi
