name: PR Verification
on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'Dockerfile'

  schedule:
    - cron: '30 2,20 * * *'

concurrency: 
  group: ${{ github.head_ref == '' && github.ref || github.head_ref }}
  cancel-in-progress: true

jobs:
  matrix-verification:
    name: Matrix Verification
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [non-emulator-verification, emulator-verification]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ${{ matrix.job }} job
        run: |
          if [ "${{ matrix.job }}" == "non-emulator-verification" ]; then
            ./scripts/run-non-emulator-verification.sh
          elif [ "${{ matrix.job }}" == "emulator-verification" ]; then
            ./scripts/run-emulator-verification.sh
          fi
        continue-on-error: true

      - name: Save ${{ matrix.job }} result
        id: save-${{ matrix.job }}-result
        run: echo "${{ matrix.job }}-result=${{ steps.${{ matrix.job }}-result.outcome }}" >> $GITHUB_ENV

  check-results:
    name: Check Results
    runs-on: ubuntu-latest
    needs: matrix-verification
    steps:
      - name: Fail if any job failed
        run: |
          if [[ "${{ env.non-emulator-verification-result }}" != "success" || "${{ env.emulator-verification-result }}" != "success" ]]; then
            echo "One of the jobs failed"
            exit 1
          fi
