name: PR Verification

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'Dockerfile'

  # schedule:
  #   - cron: '30 2,20 * * *'

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Verification Job
        uses: ./.github/workflows/pr-emulator-verification.yml

      - name: Set job status
        id: set-status
        run: |
          echo "::set-output name=${{ matrix.job }}_status::${{ job.status }}"

  monitor:
    name: Monitor Jobs
    runs-on: ubuntu-latest
    needs: verification
    steps:
      - name: Check Results
        run: |
          non_emulator_status="${{ needs.verification.outputs.non-emulator_status }}"
          emulator_status="${{ needs.verification.outputs.emulator_status }}"
          
          if [ "$non_emulator_status" == "failure" ]; then
            echo "Non Emulator Verification failed. Canceling Emulator Verification..."
            gh run cancel --job-name emulator --repo ${{ github.repository }}
          elif [ "$emulator_status" == "failure" ]; then
            echo "Emulator Verification failed. Canceling Non Emulator Verification..."
            gh run cancel --job-name non-emulator --repo ${{ github.repository }}
          fi
