name: PR Verification
on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'Dockerfile'

  schedule:
    - cron: '30 2,20 * * *'

concurrency: 
  group: ${{ github.head_ref == '' && github.ref || github.head_ref }}
  cancel-in-progress: true

jobs:
  non-emulator-verification:
    name: Non Emulator Verification
    uses: ./.github/workflows/pr-non-emulator-verification.yml
    secrets: inherit

  emulator-verification:
    name: Emulator Verification
    uses: ./.github/workflows/pr-emulator-verification.yml
    secrets: inherit
