name: Second Test
on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hey, How are you?"
      - name: Say GoodBye
        run: echo "Nice to see you Man"
