name: Source WF
run-name: Source WF (${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Nightly' }} Run)
on:
  workflow_dispatch:

  # schedule:
  #   - cron: '0 22 * * *'
    # - cron: '0 1 * * 2-6'

jobs:
  first-wf:
    name: First WF
    uses: ./.github/workflows/target.yml
    secrets: inherit
    with:
      platform: Amazon
      deviceNames: 'JP'

  second-wf:
    name: second WF
    uses: ./.github/workflows/target2.yml
    secrets: inherit
    with:
      platform: Google
      deviceNames: 'US'
