name: Source WF
on:
  workflow_dispatch:

  schedule:
    - cron: '0 1 * * 2-6'

jobs:
  apk-builder-mobile:
    name: APK Builder Mobile
    uses: ./.github/workflows/target.yml
    secrets: inherit
