name: APK Builder Manual / Nightly
run-name: ${{ github.event_name == 'workflow_dispatch' && 'APK Builder Manual Run' || 'APK Builder Nightly Run' }}
on:
  workflow_dispatch:

  schedule:
    - cron: '0 1 * * 2-6'

jobs:
  apk-builder-mobile:
    name: APK Builder Mobile
    uses: ./.github/workflows/target.yml
    secrets: inherit
