name: Source
run-name: ${{ github.event_name == 'workflow_dispatch' && 'APK Builder Manual Run' || 'APK Builder Nightly Run' }}
on:
  workflow_dispatch:

  schedule:
    - cron: '0 1 * * 2-6'

jobs:
  ui-automator-amazon:
    name: UI Automator Amazon
    uses: ./.github/workflows/target.yml
    with:
      platform: Amazon
      deviceNames: 'JP'
