name: Source
on:
  workflow_dispatch:

jobs:
  ui-automator-amazon:
    name: UI Automator Amazon
    uses: ./.github/workflows/target.yml
    secrets: inherit
    with:
      platform: Amazon
      deviceNames: 'JP'
