name: Target
on:
  workflow_call:
  
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.platform }}
      - run: echo ${{ github.event.deviceNames }}
