name: Target 2 WF
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      platform:
        description: "Platform name"
        type: string
        required: true
      deviceNames:
        description: "Device names"
        type: string
        required: true
  workflow_run:
    workflows: ["Secnd Cron Job"]
    types:
      - completed
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World this ran from first CRON GHA"

      - name: Print Goodbye
        run: echo "Done- Bye!!"

      - name: Print Platform
        run: echo ${{ inputs.platform }}

      - name: Print Device names
        run: echo ${{ inputs.deviceNames }}
