name: Target
on:
  workflow_call:
    inputs:
      platform: ${{ github.event.platform }}
      deviceNames: ${{ github.event.deviceNames }}
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.platform }}
      - run: echo ${{ github.event.deviceNames }}
