name: Test 6
run-name: Test 6 - (${{ inputs.deviceNames }}) (${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Nightly' }} Run)
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'The tag of the image to use for the container'
        required: true
        type: string
        default: latest
      deviceNames:
        description: "Device names"
        type: string
        required: true
        default: CA,IT,US,ES,JP,DACH,BR,GB
        
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World this ran from first CRON GHA"

      - name: Print Goodbye
        run: echo "Done- Bye!!"

      - name: Print Device names
        run: echo ${{ inputs.deviceNames }}

      - name: Print if CA is selected
        if: ${{ contains(inputs.deviceNames, 'CA') }}
        run: echo ${{ inputs.deviceNames }}

      - name: Install APK (CA)
        if: ${{ contains(inputs.deviceNames, 'CA') }}
        id: install-apks-ca
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (CA)
        if: ${{ contains(inputs.deviceNames, 'CA') }}
        id: run-tests-ca
        run: echo ${{ inputs.deviceNames }}

      - name: Install APK (IT)
        if: ${{ contains(inputs.deviceNames, 'IT') }}
        id: install-apks-it
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (IT)
        if: ${{ contains(inputs.deviceNames, 'IT') }}
        id: run-tests-it
        run: echo ${{ inputs.deviceNames }}
        
      - name: Fail the job
        run: exit 1

      - name: Install APK (US)
        if: always() && ${{ contains(inputs.deviceNames, 'US') }}
        id: install-apks-us
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (US)
        if: ${{ contains(inputs.deviceNames, 'US') }}
        id: run-tests-us
        run: echo ${{ inputs.deviceNames }}

      - name: Install APK (ES)
        if: ${{ contains(inputs.deviceNames, 'ES') }}
        id: install-apks-es
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (ES)
        if: ${{ contains(inputs.deviceNames, 'ES') }}
        id: run-tests-es
        run: echo ${{ inputs.deviceNames }}

      - name: Install APK (JP)
        if: ${{ contains(inputs.deviceNames, 'JP') }}
        id: install-apks-jp
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (JP)
        if: ${{ contains(inputs.deviceNames, 'JP') }}
        id: run-tests-jp
        run: echo ${{ inputs.deviceNames }}

      - name: Install APK (DACH)
        if: ${{ contains(inputs.deviceNames, 'DACH') }}
        id: install-apks-dach
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (DACH)
        if: ${{ contains(inputs.deviceNames, 'DACH') }}
        id: run-tests-dach
        run: echo ${{ inputs.deviceNames }}

      - name: Install APK (BR)
        if: ${{ contains(inputs.deviceNames, 'BR') }}
        id: install-apks-br
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (BR)
        if: ${{ contains(inputs.deviceNames, 'BR') }}
        id: run-tests-br
        run: echo ${{ inputs.deviceNames }}

      - name: Install APK (GB)
        if: ${{ contains(inputs.deviceNames, 'GB') }}
        id: install-apks-gb
        run: echo ${{ inputs.deviceNames }}

      - name: Run Tests (GB)
        if: ${{ contains(inputs.deviceNames, 'GB') }}
        id: run-tests-gb
        run: echo ${{ inputs.deviceNames }}
