name: Test Builder
on:
  workflow_dispatch:
    inputs:
      flavour-store:
        description: 'Choose store'
        required: true
        type: choice
        options:
          - Google
          - Amazon
          - Huawei
jobs:
  login-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Print output
        run: |
          echo 'console.log("${{ github.event.inputs.flavour-store }}".toLowerCase())'
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.event.inputs.flavour-store }}
      - id: step2
        run: echo ${{ steps.string.outputs.lowercase }}
      - name: Test with Bash
        shell: bash
        run: echo "THIS IS MY DATA" | tr '[:upper:]' '[:lower:]'
