name: Test - 9 - Example Workflow

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # paths-ignore:
    #   - 'Dockerfile'

jobs:
  check-dockerfile-change:
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.check-dockerfile-change.outputs.dockerfile_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes in Dockerfile
        id: check_changes
        run: |
          git fetch --depth=2 # Ensure we have enough history
          if git diff --name-only HEAD^ HEAD | grep -q '^Dockerfile$'; then
            echo "Dockerfile has changed"
            echo "::set-output name=dockerfile_changed::true"
          else
            echo "Dockerfile has not changed"
            echo "::set-output name=dockerfile_changed::false"
          fi

      - name: Run if Dockerfile changed
        if: steps.check_changes.outputs.dockerfile_changed == 'true'
        run: echo "This step runs because the Dockerfile has changed."

      - name: Run if Dockerfile did not change
        if: steps.check_changes.outputs.dockerfile_changed == 'false'
        run: echo "This step runs because the Dockerfile has not changed."
        
  build-image:
    # if: ${{ needs.check-dockerfile-change.outputs.dockerfile_changed == 'true' }}
    needs: [check-dockerfile-change]
    runs-on: ubuntu-latest
    steps:
      - name: Run if Dockerfile changed
        if: needs.check-dockerfile-change.outputs.dockerfile_changed == 'true'
        run: echo "This step runs because the Dockerfile has changed."

      - name: Run if Dockerfile did not change
        if: needs.check-dockerfile-change.outputs.dockerfile_changed == 'false'
        run: echo "This step runs because the Dockerfile has not changed."
