name: Test - 9 - Example Workflow

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # paths-ignore:
    #   - 'Dockerfile'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in Dockerfile file
        id: file_check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'Dockerfile'; then
            echo "::set-output name=run_job::true"
          else
            echo "::set-output name=run_job::false"
          fi

      - name: Conditional step
        if: steps.file_check.outputs.run_job == 'true'
        run: echo "This job runs only when there's some change in 'Dockerfile'."
