name: Test 5

on: workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: Get Commit Hash
        run: echo "$(git rev-parse HEAD)"

      - name: Test
        run: echo "_This is a test_" | sed s/_/:/g

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      #   id: extract_branch

      - name: Get the latest commit hash
        id: commit-hash
        run: echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}/vish" | sed s/'/'/-/g >> $GITHUB_OUTPUT

      - name: Show the Branch & Hash
        run: echo "Branch - ${{ steps.extract_branch.outputs.branch }} & Hash - ${{ steps.commit-hash.outputs.commitHash }}"
