name: Workflow 2

on:
  workflow_call:

jobs:
  wf2:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "I'm workflow 2"

      - name: Workflow repo
        run: echo ${{ github.repository }}

      - name: To sleep
        run: sleep 5

      - name: Install GitHub CLI
        if: failure()
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          ls -a
          gh auth status
          
      - name: Using GH cli
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: gh run cancel ${{ github.run_id }}

      - name: I always run
        if: always()
        run: echo "I told you I always run"
